
PImage body;
PImage head;
PImage foot;
PImage tail1;
PImage tail2;
PImage tail3;
PImage tail4;
PImage tail5;
PImage tail6;
PImage bomber;
PImage plane2;
PImage plane4;
PImage dragonHead;
PImage dragonTail;
PImage dragonBody;
PImage bomb;
PImage envelope;
PImage basket;
PImage gunBarrel;
PImage trieb;
PImage triebF1;
PImage triebF2;
PImage triebF3;
PImage triebF4;
PImage triebProp;
PImage triebJet1;
PImage triebJet2;
PImage triebJet3;
PImage fortress;
PImage fortressPropF1;
PImage fortressPropF2;
PImage fortressGun;
PImage pod;
PImage podThruster1;
PImage podThruster2;
PImage biplane;
PImage biplanePropF1;
PImage biplanePropF2;
PImage biplanePropF3;
PImage warPlane;
PImage warPlanePropF1;
PImage warPlanePropF2;
PImage warPlanePropF3;
PImage heli;
PImage heliProp;

PImage archer;
PImage dart;
PImage gunner;
PImage shotGunner;
PImage heavyGunner;
PImage swarmer;
PImage bug;
PImage mine;
PImage shield;
PImage flagShip;

PImage logo;
PImage logo2;

void loadImages(){
  body=loadImage("nyanBody.png");
  head=loadImage("nyanHead.png");
  foot=loadImage("nyanFoot.png");
  tail1=loadImage("nyanTailF1.png");
  tail2=loadImage("nyanTailF2.png");
  tail3=loadImage("nyanTailF3.png");
  tail4=loadImage("nyanTailF4.png");
  tail5=loadImage("nyanTailF5.png");
  bomber=loadImage("bomber.png");
  plane2=loadImage("plane2.png");
  plane4=loadImage("plane4.png");
  dragonHead=loadImage("dragonHead.png");
  dragonTail=loadImage("dragonTail.png");
  dragonBody=loadImage("dragonBody.png");
  bomb=loadImage("bomb.png");
  envelope=loadImage("balloonEnvelope.png");
  basket=loadImage("balloonBasket.png");
  gunBarrel=loadImage("balloonGun.png");
  trieb=loadImage("triebflugel.png");
  triebF1=loadImage("triebflugelPropF1.png");
  triebF2=loadImage("triebflugelPropF2.png");
  triebF3=loadImage("triebflugelPropF3.png");
  triebF4=loadImage("triebflugelPropF4.png");
  triebProp=loadImage("triebflugelPropWing.png");
  triebJet1=loadImage("triebflugelPropJet1.png");
  triebJet2=loadImage("triebflugelPropJet2.png");
  triebJet3=loadImage("triebflugelPropJet3.png");
  fortress=loadImage("flyingFortress2.png");
  fortressPropF1=loadImage("flyingFortressPropF1.png");
  fortressPropF2=loadImage("flyingFortressPropF2.png");
  fortressGun=loadImage("flyingFortressGun.png");
  pod=loadImage("pod.png");
  podThruster1=loadImage("podThruster1.png");
  podThruster2=loadImage("podThruster2.png");
  biplane=loadImage("biplane.png");
  biplanePropF1=loadImage("biplanePropF1.png");
  biplanePropF2=loadImage("biplanePropF2.png");
  biplanePropF3=loadImage("biplanePropF3.png");
  warPlane=loadImage("warplane.png");
  warPlanePropF1=loadImage("warplanePropF1.png");
  warPlanePropF2=loadImage("warplanePropF2.png");
  warPlanePropF3=loadImage("warplanePropF3.png");
  heli=loadImage("helicopter.png");
  heliProp=loadImage("helicopterProp.png");
  
  archer=loadImage("alien_archer.png");
  dart=loadImage("alien_dart.png");
  gunner=loadImage("alien_gunner.png");
  shotGunner=loadImage("alien_shotgunner.png");
  heavyGunner=loadImage("alien_heavygunner.png");
  swarmer=loadImage("alien_swarmer.png");
  bug=loadImage("alien_bug.png");
  mine=loadImage("alien_mine.png");
  shield=loadImage("alien_shield.png");
  flagShip=loadImage("flagship.png");
  
  logo=loadImage("logo.png");
  logo2=loadImage("logo2.png");
}
